
Vagrant.configure("2") do |config|

  config.vm.define "master1" do |master1|
    master1.vm.box = "ubuntu/xenial64"
    master1.vm.hostname = 'master1'

    master1.vm.network :private_network, ip: "192.168.56.101"
    master1.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"

    master1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "master1"]
    end
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "ubuntu/xenial64"
    worker1.vm.hostname = 'worker1'

    worker1.vm.network :private_network, ip: "192.168.56.102"

    worker1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "worker1"]
    end
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/xenial64"
    worker2.vm.hostname = 'worker2'

    worker2.vm.network :private_network, ip: "192.168.56.103"

    worker2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "worker2"]
    end
  end

end

